name: 'Release new version 🚀'

on: push

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: myparcelnl/actions/yarn-install@v5
        with:
          node-version: 18

      - name: 'Build'
        run: |
          yarn build

      - uses: myparcelnl/actions/semantic-release@v5
        with:
          token: ${{ secrets.GH_REPO_TOKEN }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
